import requests,json,time,threading,os,sys
import urllib.request, os, threading, time, random, sys
import colorama
from colorama import Fore, Style, init
#from requests_futures.sessions import FuturesSession
#from requests_futures import sessions
os.system("clear")
os.system("figlet Login")
print(Fore.RED + "สแปม Gmail <BY Aimbot>")
print("")
gmail_input = input(Fore.GREEN + "อีเมลล์ที่จะยิง => ")
jum_input = int(input(Fore.BLUE + "จำนวน => "))
time.sleep(5)
print("")
print(Fore.YELLOW + "เริ่มยิง :")
time.sleep(5)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
time.sleep(4)
print(Fore.YELLOW + "ยิงสำเร็จ")
